apiVersion: tekton.dev/v1
kind: Task
metadata:
  creationTimestamp: '2025-02-02T12:46:05Z'
  generation: 2
  managedFields:
    - apiVersion: tekton.dev/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:params': {}
          'f:steps': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2025-02-02T14:11:50Z'
  name: jumpstarter-release-lease-test
  namespace: demo
  resourceVersion: '19323634'
  uid: da12532b-d8f6-44b9-b8fc-a2d807642730
spec:
  params:
    - description: The lease to be released.
      name: jmp-lease-id
      type: string
    - default: default
      description: The client intending to release the lease.
      name: client-name
      type: string
  steps:
    - computeResources: {}
      image: 'quay.io/jumpstarter-dev/jumpstarter:latest'
      name: release-lease
      script: |
        #!/bin/bash
          set -eux

         # Set the lease ID from the pipeline parameter into the environment variable
         export JMP_LEASE_ID=$(params.jmp-lease-id)
         echo "Using Jumpstarter client configuration: $(params.client-name)"

         # Switch to the specified Jumpstarter client configuration
         jmp client use-config "$(params.client-name)"

         # Release the lease associated with the provided lease ID
         echo "Releasing lease: $JMP_LEASE_ID"
         jmp client lease release -l "$JMP_LEASE_ID"

         # Confirm release
         echo "Lease $JMP_LEASE_ID has been successfully released."
  workspaces:
    - mountPath: /root/.config/jumpstarter/clients
      name: jumpstarter-client-secret
